"""added some changes in the image model

Revision ID: 183b5ddb6d21
Revises: 768f57393836
Create Date: 2023-09-14 16:01:00.907409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '183b5ddb6d21'
down_revision = '768f57393836'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('html_code', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('style', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('font', sa.String(length=64), nullable=True))
        batch_op.drop_column('text')
        batch_op.drop_column('name')
        batch_op.drop_column('html_text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('html_text', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('text', sa.TEXT(), nullable=True))
        batch_op.drop_column('font')
        batch_op.drop_column('style')
        batch_op.drop_column('html_code')
        batch_op.drop_column('code')

    # ### end Alembic commands ###
