"""empty message

Revision ID: 2d49d96778d5
Revises: 183b5ddb6d21
Create Date: 2023-09-15 17:03:06.604556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d49d96778d5'
down_revision = '183b5ddb6d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('highlighted_code', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('style_definitions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('style_bg_color', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('current_lang', sa.String(length=64), nullable=True))
        batch_op.drop_column('html_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('html_code', sa.TEXT(), nullable=True))
        batch_op.drop_column('current_lang')
        batch_op.drop_column('style_bg_color')
        batch_op.drop_column('style_definitions')
        batch_op.drop_column('highlighted_code')

    # ### end Alembic commands ###
