"""added

Revision ID: bf09a9ccd8f6
Revises: 7946a69160a5
Create Date: 2023-09-15 20:33:07.907626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf09a9ccd8f6'
down_revision = '7946a69160a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.alter_column('image_file',
               existing_type=sa.BLOB(),
               type_=sa.String(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.alter_column('image_file',
               existing_type=sa.String(length=128),
               type_=sa.BLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
